### ISSUE TITLE
iOS/Android app plan

### ISSUE THREAD

**Issue by peeyush1234** [usevolition/volition#44]
Love the project. (I always wanted a tool to reflect on daily goals) 

I was wondering if there are any plans to launch an iOS/Android app. It would be nice to have the Volition app.

**Comment by peeyush1234** [comment]
If you are thinking of building an app, please let me know if I can help. I have some experience with ReactNative.

**Comment by harshamurthy** [comment]
@peeyush1234, we don't have any plans to make native apps for iOS/Android. We're big fans of the device-agnostic nature of mobile first web applications. For now, you can add Volition as a home screen bookmark on your phone.

If we do ever decide to build native versions, we'll definitely let you know!
