### ISSUE TITLE
Heroku install doesn't provide login info

### ISSUE THREAD

**Issue by githubber** [usevolition/volition#49]
I've deployed to heroku using the nice little Heroku button, and it works it's magic, but there is no indication and what the initial login info is. How, or where, do I find this?

**Comment by garrettqmartin8** [comment]
Hey @githubber. There's no default login, but you can sign up just like you would on the hosted version of the app. You'll just have the only user account on the self-hosted version of Volition 😄

**Comment by githubber** [comment]
Hm, whenever I have tried a message appears on the subsequent screen telling me:
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

But the logs don't tell me anything that I understand! But when I try again then message tells me the email address is already in use, so I try to log in and the same error message as above pops up.

Here are some lines that might give a hint:
`2017-09-20T03:06:53.839344+00:00 app[web.1]: [94116538-b539-42fd-8d18-feda9f47b9c2] Completed 500 Internal Server Error in 101ms (ActiveRecord: 6.7ms)
2017-09-20T03:06:53.841089+00:00 app[web.1]: [94116538-b539-42fd-8d18-feda9f47b9c2]   
2017-09-20T03:06:53.841189+00:00 app[web.1]: [94116538-b539-42fd-8d18-feda9f47b9c2] NoMethodError (undefined method `id' for false:FalseClass):`

**Comment by githubber** [comment]
I haven't entered any details for email yet, could this be causing the error if the app is supposed to email the newly registered user their details or confirmation?

**Comment by githubber** [comment]
`2017-09-20T03:32:56.590406+00:00 app[web.1]: [97cad628-88d2-4e7a-82a6-98778fd66d3b] Completed 500 Internal Server Error in 123ms (ActiveRecord: 7.9ms)
2017-09-20T03:32:56.592252+00:00 app[web.1]: [97cad628-88d2-4e7a-82a6-98778fd66d3b]   
2017-09-20T03:32:56.592356+00:00 app[web.1]: [97cad628-88d2-4e7a-82a6-98778fd66d3b] NoMethodError (undefined method `id' for false:FalseClass):`

**Comment by garrettqmartin8** [comment]
@githubber I'll definitely look into this. Thanks for the details!

**Comment by githubber** [comment]
For what's worth, I tried installing a new instance on Heroku using the Europe location and the app works properly. Let me make a new account, I saw the welcome and intro text from yourself, and coudl then use the app.

**Comment by harshamurthy** [comment]
Awesome @githubber. Thanks for figuring that out, will definitely make a note of it.
